<a href="https://colab.research.google.com/github/Dalvisneha12/IBM_AIMI_Cloud_python/blob/main/Numpy%26pandas_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

array2 =np.array([12,34,56,82])

In [ ]:
array2


array([12, 34, 56, 82])

In [ ]:
array2[2]

56

In [ ]:
array2[1:3]

array([34, 56])

In [ ]:
array2[1]='hari'

ValueError: ignored

In [ ]:
array2[1]=13
array2

array([12, 13, 56, 82])

In [ ]:
array2.ndim
# type of dimension

1

In [ ]:
type(array2)


numpy.ndarray

In [ ]:
array1=np.array([[12,23,54],[32,45,46]])
array1

array([[12, 23, 54],
       [32, 45, 46]])

In [ ]:
array1.ndim


2

In [ ]:
array1[1][0:2] # slicing and indexing

array([32, 45])

In [ ]:
# functions and Methods
array1.dtype


dtype('int64')

In [ ]:
type(array2)

numpy.ndarray

In [ ]:
np.linspace(12,34,16) # methods in numpy

array([12.        , 13.46666667, 14.93333333, 16.4       , 17.86666667,
       19.33333333, 20.8       , 22.26666667, 23.73333333, 25.2       ,
       26.66666667, 28.13333333, 29.6       , 31.06666667, 32.53333333,
       34.        ])

In [ ]:
#pandas---> (Series, DataFrame)
demo1 = pd.Series(np.arange(3,6))
demo1


0    3
1    4
2    5
dtype: int64

In [ ]:
demo2 = pd.Series(np.arange(13,16))
demo2

0    13
1    14
2    15
dtype: int64

In [ ]:
demo3=pd.DataFrame(demo1,demo2)
demo3

ValueError: ignored

In [ ]:
dummy = {'Name':['hari','samya','srikant','shivam',np.nan],
         'Age': [27,36,np.nan,29,25],
         'Track': ('AI','ML','CAD',np.nan,np.nan)}
dummy

{'Name': ['hari', 'samya', 'srikant', 'shivam', nan],
 'Age': [27, 36, nan, 29, 25],
 'Track': ('AI', 'ML', 'CAD', nan, nan)}

In [ ]:
df = pd.DataFrame(dummy)
df

Name   Age Track
0     hari  27.0    AI
1    samya  36.0    ML
2  srikant   NaN   CAD
3   shivam  29.0   NaN
4      NaN  25.0   NaN

from matplotlib import pyplot as plt
df['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('Track').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Track'].value_counts()
    for x_label, grp in df.groupby('Name')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Name')
_ = plt.ylabel('Track')

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Name'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='Name', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(df['Track'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(df, x='Age', y='Track', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
df = pd.DataFrame(dummy)
df

Name   Age Track
0     hari  27.0    AI
1    samya  36.0    ML
2  srikant   NaN   CAD
3   shivam  29.0   NaN
4      NaN  25.0   NaN

In [ ]:
# to call only single columns, how to chech null values, how to replace null value, find the Data type
df

Name   Age Track
0     hari  27.0    AI
1    samya  36.0    ML
2  srikant   NaN   CAD
3   shivam  29.0   NaN
4      NaN  25.0   NaN

In [ ]:
df.Name

0       hari
1      samya
2    srikant
3     shivam
4        NaN
Name: Name, dtype: object

In [ ]:
df['Name']# prefered method

0       hari
1      samya
2    srikant
3     shivam
4        NaN
Name: Name, dtype: object

In [ ]:
# column as features
# row as observation

In [ ]:
# how to find DB
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.info()  # info is the method name we get in details

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    4 non-null      object 
 1   Age     4 non-null      float64
 2   Track   3 non-null      object 
dtypes: float64(1), object(2)
memory usage: 248.0+ bytes


In [ ]:
# always covnvert object into Interger
df.isnull()  # output in boolean

Name    Age  Track
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False   True
4   True  False   True

In [ ]:
df.isnull().sum()
# we will be gettibg column name and total null values

Name     1
Age      1
Track    2
dtype: int64

In [ ]:
# loc & iloc
df.loc[: , :]  # repsersent column and rows

Name   Age Track
0     hari  27.0    AI
1    samya  36.0    ML
2  srikant   NaN   CAD
3   shivam  29.0   NaN
4      NaN  25.0   NaN

In [ ]:
df.loc[0:2,'Name':'Age']

Name   Age
0     hari  27.0
1    samya  36.0
2  srikant   NaN

In [ ]:
df.iloc[0:3,0:2] # prefered

Name   Age
0     hari  27.0
1    samya  36.0
2  srikant   NaN

In [2]:
!unzip '/content/archive (30).zip

/bin/bash: -c: line 1: unexpected EOF while looking for matching `''
/bin/bash: -c: line 2: syntax error: unexpected end of file


# **Basic** **Preprocessing**

In [3]:
!unzip '/content/ObesityDataSet.csv.zip'

unzip:  cannot find or open /content/ObesityDataSet.csv.zip, /content/ObesityDataSet.csv.zip.zip or /content/ObesityDataSet.csv.zip.ZIP.


In [5]:
df = pd.read_csv('/content/ObesityDataSet.csv')
df.head()

NameError: ignored

In [6]:
df = pd .read_csv('/content/ObesityDataSet.csv')
df.head()

NameError: ignored

In [7]:
!unzip'/content/archive (30).zip'


/bin/bash: line 1: unzip/content/archive (30).zip: No such file or directory


In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd .read_csv('/content/ObesityDataSet.csv')
df.head()

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no   2.0   
1  Female  21.0    1.52    56.0                            yes   no   3.0   
2    Male  23.0    1.80    77.0                            yes   no   2.0   
3    Male  27.0    1.80    87.0                             no   no   3.0   
4    Male  22.0    1.78    89.8                             no   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II

In [19]:
df['Gender'].value_counts()

0    1068
1    1043
Name: Gender, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Gender                          2111 non-null   object 
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object 
 5   FAVC                            2111 non-null   object 
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object 
 9   SMOKE                           2111 non-null   object 
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object 
 12  FAF                             21

In [ ]:
# Encoding the data  ( why to convery object in to numerial values) becaause AIML is in numericalvalues so we convert object into numerial value to work on datasets.

In [ ]:
# 1) label encoding 2) one hot encoding 3) manual encoding

In [12]:
df['Gender'].value_counts()

Male      1068
Female    1043
Name: Gender, dtype: int64

In [15]:
df.head(3)

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0       1  21.0    1.62    64.0                            yes   no   2.0   
1       1  21.0    1.52    56.0                            yes   no   3.0   
2       0  23.0    1.80    77.0                            yes   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   

                  MTRANS     NObeyesdad  
0  Public_Transportation  Normal_Weight  
1  Public_Transportation  Normal_Weight  
2  Public_Transportation  Normal_Weight

In [17]:
#Manual Encoding
df['Gender'] =df['Gender'].replace({'Male':0,'Female':1})

In [18]:
df.head(3)

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0       1  21.0    1.62    64.0                            yes   no   2.0   
1       1  21.0    1.52    56.0                            yes   no   3.0   
2       0  23.0    1.80    77.0                            yes   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   

                  MTRANS     NObeyesdad  
0  Public_Transportation  Normal_Weight  
1  Public_Transportation  Normal_Weight  
2  Public_Transportation  Normal_Weight

In [20]:
df['FAVC'].value_counts()

yes    1866
no      245
Name: FAVC, dtype: int64

In [22]:
df['FAVC'] = df['FAVC'].replace({'yes':1,'no':0})

In [23]:
df.head(2)

Gender   Age  Height  Weight family_history_with_overweight  FAVC  FCVC  \
0       1  21.0    1.62    64.0                            yes     0   2.0   
1       1  21.0    1.52    56.0                            yes     0   3.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE       CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0         no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0  Sometimes   

                  MTRANS     NObeyesdad  
0  Public_Transportation  Normal_Weight  
1  Public_Transportation  Normal_Weight

In [26]:
df['family_history_with_overweight'].value_counts()

yes    1726
no      385
Name: family_history_with_overweight, dtype: int64

In [27]:
df['family_history_with_overweight'] = df['family_history_with_overweight'].replace({'yes':1,'no':0})

In [28]:
df.head(2)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       1  21.0    1.62    64.0                               1     0   2.0   
1       1  21.0    1.52    56.0                               1     0   3.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE       CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0         no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0  Sometimes   

                  MTRANS     NObeyesdad  
0  Public_Transportation  Normal_Weight  
1  Public_Transportation  Normal_Weight

In [ ]:
# one hot Encoding only convert it to 0 either 1

In [29]:
pd.get_dummies(df['CAEC'])

Always  Frequently  Sometimes  no
0          0           0          1   0
1          0           0          1   0
2          0           0          1   0
3          0           0          1   0
4          0           0          1   0
...      ...         ...        ...  ..
2106       0           0          1   0
2107       0           0          1   0
2108       0           0          1   0
2109       0           0          1   0
2110       0           0          1   0

[2111 rows x 4 columns]

In [30]:
df['CAEC'].value_counts()  # convert caterory into columns # one hot encoding

Sometimes     1765
Frequently     242
Always          53
no              51
Name: CAEC, dtype: int64

In [ ]:
Which one is better from  above three
lable : automatically the value will be assigned
# LABLE ENCODING SKLEARN LIBARY is been used (label encoder comes under sklearn package)

In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
le = LabelEncoder() # initialization of module # assignment value Alphabetical oredr

In [35]:
df['CAEC'] =le.fit_transform(df['CAEC'])

In [36]:
df.head(3)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       1  21.0    1.62    64.0                               1     0   2.0   
1       1  21.0    1.52    56.0                               1     0   3.0   
2       0  23.0    1.80    77.0                               1     0   2.0   

   NCP  CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC                 MTRANS  \
0  3.0     2    no   2.0   no  0.0  1.0          no  Public_Transportation   
1  3.0     2   yes   3.0  yes  3.0  0.0   Sometimes  Public_Transportation   
2  3.0     2    no   2.0   no  2.0  1.0  Frequently  Public_Transportation   

      NObeyesdad  
0  Normal_Weight  
1  Normal_Weight  
2  Normal_Weight

In [ ]:
# Hari # Srikanth # Saumya ( follow alphabetical order )
#  0 #    2    # 1   # this  is how label encoder work

In [37]:
df['CALC']. value_counts()

Sometimes     1401
no             639
Frequently      70
Always           1
Name: CALC, dtype: int64

In [38]:
df['CALC'] =le.fit_transform(df['CALC'])

In [39]:
df.head(3)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       1  21.0    1.62    64.0                               1     0   2.0   
1       1  21.0    1.52    56.0                               1     0   3.0   
2       0  23.0    1.80    77.0                               1     0   2.0   

   NCP  CAEC SMOKE  CH2O  SCC  FAF  TUE  CALC                 MTRANS  \
0  3.0     2    no   2.0   no  0.0  1.0     3  Public_Transportation   
1  3.0     2   yes   3.0  yes  3.0  0.0     2  Public_Transportation   
2  3.0     2    no   2.0   no  2.0  1.0     1  Public_Transportation   

      NObeyesdad  
0  Normal_Weight  
1  Normal_Weight  
2  Normal_Weight

In [41]:
df['SMOKE']. value_counts()

no     2067
yes      44
Name: SMOKE, dtype: int64

In [42]:
df['SMOKE'] =le.fit_transform(df['SMOKE'])

In [43]:
df.head(3)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       1  21.0    1.62    64.0                               1     0   2.0   
1       1  21.0    1.52    56.0                               1     0   3.0   
2       0  23.0    1.80    77.0                               1     0   2.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC                 MTRANS  \
0  3.0     2      0   2.0   no  0.0  1.0     3  Public_Transportation   
1  3.0     2      1   3.0  yes  3.0  0.0     2  Public_Transportation   
2  3.0     2      0   2.0   no  2.0  1.0     1  Public_Transportation   

      NObeyesdad  
0  Normal_Weight  
1  Normal_Weight  
2  Normal_Weight

In [44]:
df['CH2O']. value_counts()

2.000000    448
1.000000    211
3.000000    162
2.825629      3
1.636326      3
           ... 
1.622638      1
2.452986      1
2.035954      1
1.944095      1
2.863513      1
Name: CH2O, Length: 1268, dtype: int64

In [46]:
df['CH2O'] =le.fit_transform(df['CH2O'])

In [47]:
df.head(3)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       1  21.0    1.62    64.0                               1     0   2.0   
1       1  21.0    1.52    56.0                               1     0   3.0   
2       0  23.0    1.80    77.0                               1     0   2.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC                 MTRANS  \
0  3.0     2      0   549   no  0.0  1.0     3  Public_Transportation   
1  3.0     2      1  1267  yes  3.0  0.0     2  Public_Transportation   
2  3.0     2      0   549   no  2.0  1.0     1  Public_Transportation   

      NObeyesdad  
0  Normal_Weight  
1  Normal_Weight  
2  Normal_Weight

In [48]:
df['SCC']. value_counts()

no     2015
yes      96
Name: SCC, dtype: int64

In [49]:
df['SCC'] =le.fit_transform(df['SCC'])

In [50]:
df.head(3)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       1  21.0    1.62    64.0                               1     0   2.0   
1       1  21.0    1.52    56.0                               1     0   3.0   
2       0  23.0    1.80    77.0                               1     0   2.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC                 MTRANS  \
0  3.0     2      0   549    0  0.0  1.0     3  Public_Transportation   
1  3.0     2      1  1267    1  3.0  0.0     2  Public_Transportation   
2  3.0     2      0   549    0  2.0  1.0     1  Public_Transportation   

      NObeyesdad  
0  Normal_Weight  
1  Normal_Weight  
2  Normal_Weight

In [51]:
df['MTRANS']. value_counts()

Public_Transportation    1580
Automobile                457
Walking                    56
Motorbike                  11
Bike                        7
Name: MTRANS, dtype: int64

In [52]:
df['MTRANS'] =le.fit_transform(df['MTRANS'])

In [53]:
df.head(3)

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       1  21.0    1.62    64.0                               1     0   2.0   
1       1  21.0    1.52    56.0                               1     0   3.0   
2       0  23.0    1.80    77.0                               1     0   2.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS     NObeyesdad  
0  3.0     2      0   549    0  0.0  1.0     3       3  Normal_Weight  
1  3.0     2      1  1267    1  3.0  0.0     2       3  Normal_Weight  
2  3.0     2      0   549    0  2.0  1.0     1       3  Normal_Weight

In [ ]:
# retrive the original data

In [54]:
le.inverse_transform([3])

array(['Public_Transportation'], dtype=object)